- name: Create user on different Linux and Win os
  hosts: all
  tasks:
    - name: Create user on Ubuntu/Debian
      ansible.builtin.user:
        name: "{{ item.username }}"
        shell: /bin/bash
        groups: sudo
        append: yes
        state: present
        password: "{{ item.password | password_hash('sha512') }}"

        create_home: yes
      when: ansible_facts.os_family == "Debian"
      loop: "{{users}}"

    - name: Create user on Fedora
      ansible.builtin.user:
        name: "{{ item.username }}"
        shell: /bin/bash
        groups: wheel
        append: yes
        state: present
        password: "{{ item.password | password_hash('sha512') }}"
        create_home: yes
      when: ansible_facts.os_family in ["RedHat", "Fedora"]
      loop: "{{users}}"

    - name: Create a user on Windows Server
      ansible.windows.win_user:
        name: "{{item.username}}"
        fullname: "{{item.fullname}}"
        password: "{{ item.password }}"
        state: present
        groups:
         - Users
         - Administrators
      when: ansible_facts['os_family'] == "Windows"
      loop: "{{users}}"


    - name: Force users to change password on next login
      command: chage -d 0 {{ item.username }}  # The chage -d 0 command forces the user to change their password upon the first login.
      when: ansible_facts.os_family in ["RedHat", "Debian", "SUSE", "Fedora"]
      loop: "{{ users }}"